name: Deploy ADF to Test

on:
  push:
    branches:
      - adf_publish
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - production
jobs:
  deploy-test:
    runs-on: ubuntu-latest
    environment:
      name: "test"
    steps:
      - uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          echo "Repository contents:"
          ls -R

      - name: Display GitHub Actions Path Variables
        run: |
          echo "RUNNER_WORKSPACE: $RUNNER_WORKSPACE"
          echo "GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "RUNNER_TEMP: $RUNNER_TEMP"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          echo "GITHUB_PATH: $GITHUB_PATH"
          echo "HOME: $HOME"
        shell: bash

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure PowerShell Module
        shell: pwsh
        run: |
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
          $clientId = "${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}"
          $clientSecret = "${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}"
          $tenantId = "${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}"
          $secureStringPwd = ConvertTo-SecureString $clientSecret -AsPlainText -Force
          $pscredential = New-Object System.Management.Automation.PSCredential ($clientId, $secureStringPwd)
          Connect-AzAccount -ServicePrincipal -Credential $pscredential -Tenant $tenantId

      # - name: Pre-deployment PowerShell Script
      #   shell: pwsh
      #   run: |
      #     & "./dev-ci-cd-demo-ct-adf/PrePostDeploymentScript.Ver2.ps1" `
      #      -armTemplate "./dev-ci-cd-demo-ct-adf/ARMTemplateParametersForFactory.json" `
      #      -ResourceGroupName ${{ secrets.AZURE_RESOURCE_GROUP }} `
      #      -DataFactoryName ${{ secrets.AZURE_FACTORY_NAME }} `
      #      -predeployment $true `
      #      -deleteDeployment $false

      - name: Deploy Azure Data Factory
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./dev-ci-cd-demo-ct-adf/ARMTemplateForFactory.json
          parameters: ./dev-ci-cd-demo-ct-adf/ARMTemplateParametersForFactory.json factoryName=${{ secrets.AZURE_FACTORY_NAME }}

      # - name: Post-deployment PowerShell Script
      #   shell: pwsh
      #   run: |
      #     & "./dev-ci-cd-demo-ct-adf/PrePostDeploymentScript.Ver2.ps1" `
      #      -armTemplate "./dev-ci-cd-demo-ct-adf/ARMTemplateParametersForFactory.json" `
      #      -ResourceGroupName ${{ secrets.AZURE_RESOURCE_GROUP }} `
      #      -DataFactoryName ${{ secrets.AZURE_FACTORY_NAME }} `
      #      -predeployment $false `
      #      -deleteDeployment $true

  pre-approve-production:
    needs: deploy-test
    if: github.event.inputs.environment == 'production'
    runs-on: ubuntu-latest
    environment:
      name: production-approval
      # The actual reviewers are set in the GitHub environment settings
    steps:
      - name: Pre-approval for Production Deployment
        run: |
          echo "Waiting for manual approval before deploying to production..."
          echo "Approved reviewers can approve this deployment in the GitHub Actions interface."

  deploy-production:
    needs: pre-approve-production
    runs-on: ubuntu-latest
    environment:
      name: "production"
    steps:
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PROD_AZURE_CREDENTIALS }}

      - name: Install Azure PowerShell Module
        shell: pwsh
        run: |
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
          $clientId = "${{ fromJson(secrets.PROD_AZURE_CREDENTIALS).clientId }}"
          $clientSecret = "${{ fromJson(secrets.PROD_AZURE_CREDENTIALS).clientSecret }}"
          $tenantId = "${{ fromJson(secrets.PROD_AZURE_CREDENTIALS).tenantId }}"
          $secureStringPwd = ConvertTo-SecureString $clientSecret -AsPlainText -Force
          $pscredential = New-Object System.Management.Automation.PSCredential ($clientId, $secureStringPwd)
          Connect-AzAccount -ServicePrincipal -Credential $pscredential -Tenant $tenantId

      # - name: Pre-deployment PowerShell Script
      #   shell: pwsh
      #   run: |
      #     & "./dev-ci-cd-demo-ct-adf/PrePostDeploymentScript.Ver2.ps1" `
      #      -armTemplate "./dev-ci-cd-demo-ct-adf/ARMTemplateParametersForFactory.json" `
      #      -ResourceGroupName ${{ secrets.PROD_AZURE_RESOURCE_GROUP }} `
      #      -DataFactoryName ${{ secrets.PROD_AZURE_FACTORY_NAME }} `
      #      -predeployment $true `
      #      -deleteDeployment $false

      - name: Deploy Azure Data Factory to Production
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.PROD_AZURE_RESOURCE_GROUP }}
          template: ./dev-ci-cd-demo-ct-adf/ARMTemplateForFactory.json
          parameters: ./dev-ci-cd-demo-ct-adf/ARMTemplateParametersForFactory.json factoryName=${{ secrets.PROD_AZURE_FACTORY_NAME }}

      # - name: Post-deployment PowerShell Script
      #   shell: pwsh
      #   run: |
      #     & "./dev-ci-cd-demo-ct-adf/PrePostDeploymentScript.Ver2.ps1" `
      #      -armTemplate "./dev-ci-cd-demo-ct-adf/ARMTemplateParametersForFactory.json" `
      #      -ResourceGroupName ${{ secrets.PROD_AZURE_RESOURCE_GROUP }} `
      #      -DataFactoryName ${{ secrets.PROD_AZURE_FACTORY_NAME }} `
      #      -predeployment $false `
      #      -deleteDeployment $true
