name: Deploy ADF to Test

on:
  push:
    branches:
      - adf_publish
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: "test"
    steps:
      - uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          echo "Repository contents:"
          ls -R

      - name: Display GitHub Actions Path Variables
        run: |
          echo "RUNNER_WORKSPACE: $RUNNER_WORKSPACE"
          echo "GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "RUNNER_TEMP: $RUNNER_TEMP"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          echo "GITHUB_PATH: $GITHUB_PATH"
          echo "HOME: $HOME"
        shell: bash

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Pre-deployment PowerShell Script
      #   shell: pwsh
      #   run: |
      #     & "$env:GITHUB_WORKSPACE/PrePostDeploymentScript.Ver2.ps1" `
      #      -armTemplate "$env:GITHUB_WORKSPACE/ARMTemplateParametersForFactory.json" `
      #      -ResourceGroupName ${{ secrets.AZURE_RESOURCE_GROUP }} `
      #      -DataFactoryName ${{ secrets.AZURE_FACTORY_NAME }} `
      #      -predeployment $true `
      #      -deleteDeployment $false

      - name: Deploy Azure Data Factory
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ${{ github.repository }}/dev-ci-cd-demo-ct-adf/ARMTemplateForFactory.json
          parameters: ${{ github.repository }}/dev-ci-cd-demo-ct-adf/ARMTemplateParametersForFactory.json factoryName=${{ secrets.AZURE_FACTORY_NAME }}

      # - name: Post-deployment PowerShell Script
      #   shell: pwsh
      #   run: |
      #     & "$env:GITHUB_WORKSPACE/PrePostDeploymentScript.Ver2.ps1" `
      #      -armTemplate "$env:GITHUB_WORKSPACE/ARMTemplateParametersForFactory.json" `
      #      -ResourceGroupName ${{ secrets.AZURE_RESOURCE_GROUP }} `
      #      -DataFactoryName ${{ secrets.AZURE_FACTORY_NAME }} `
      #      -predeployment $false `
      #      -deleteDeployment $true
