name: ADF CI Option 2 Build Pipeline

on:
  push:
    branches:
      - main

env:
  SUBSCRIPTION_ID: "c0dd70cc-c4a2-4791-85d8-b30290f5af65"
  RESOURCE_GROUP: "dev-ci-cd-demo-rg"
  DATA_FACTORY: "dev-ci-cd-demo-ct-adf"
  PACKAGE_FOLDER: "build"
  ADF_ROOT_FOLDER: ""

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: "test"
    steps:
      - uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          echo "Repository contents:"
          ls -R

      - name: Display GitHub Actions Path Variables
        run: |
          echo "RUNNER_WORKSPACE: $RUNNER_WORKSPACE"
          echo "GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "RUNNER_TEMP: $RUNNER_TEMP"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          echo "GITHUB_PATH: $GITHUB_PATH"
          echo "HOME: $HOME"
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install npm packages
        run: |
          npm install

      - name: Validate Data Factory Resources
        run: |
          npm run build validate "$GITHUB_WORKSPACE/" /subscriptions/${{ env.SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ env.DATA_FACTORY }}

      - name: Generate ARM template
        run: |
          npm run build export "$GITHUB_WORKSPACE/" /subscriptions/${{ env.SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ env.DATA_FACTORY }} "ArmTemplate"

      - name: Upload ARM template as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ArmTemplates
          path: ArmTemplate

      - name: List files in the repository
        run: |
          echo "Repository contents:"
          ls -R

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure PowerShell Module
        shell: pwsh
        run: |
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
          $clientId = "${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}"
          $clientSecret = "${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}"
          $tenantId = "${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}"
          $secureStringPwd = ConvertTo-SecureString $clientSecret -AsPlainText -Force
          $pscredential = New-Object System.Management.Automation.PSCredential ($clientId, $secureStringPwd)
          Connect-AzAccount -ServicePrincipal -Credential $pscredential -Tenant $tenantId

      - name: Pre-deployment PowerShell Script
        shell: pwsh
        run: |
          & "ArmTemplate/PrePostDeploymentScript.Ver2.ps1" `
           -armTemplate "ArmTemplate/ARMTemplateParametersForFactory.json" `
           -ResourceGroupName ${{ secrets.AZURE_RESOURCE_GROUP }} `
           -DataFactoryName ${{ secrets.AZURE_FACTORY_NAME }} `
           -predeployment $true `
           -deleteDeployment $false

      - name: Deploy Azure Data Factory
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ArmTemplate/ARMTemplateForFactory.json
          parameters: ArmTemplate/ARMTemplateParametersForFactory.json factoryName=${{ secrets.AZURE_FACTORY_NAME }}

      - name: Post-deployment PowerShell Script
        shell: pwsh
        run: |
          & "ArmTemplate/PrePostDeploymentScript.Ver2.ps1" `
           -armTemplate "ArmTemplate/ARMTemplateParametersForFactory.json" `
           -ResourceGroupName ${{ secrets.AZURE_RESOURCE_GROUP }} `
           -DataFactoryName ${{ secrets.AZURE_FACTORY_NAME }} `
           -predeployment $false `
           -deleteDeployment $true
