name: Deploy ADF to Test

on:
  push:
    branches:
      - adf_publish
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: "test"
    steps:
      - uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          echo "Repository contents:"
          ls -R
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Pre-deployment PowerShell Script
        shell: pwsh
        run: |
          ${{ github.workspace }}\PrePostDeploymentScript.Ver2.ps1 `
            -armTemplate "${{ github.workspace }}/ARMTemplateParametersForFactory.json" `
            -ResourceGroupName ${{ secrets.AZURE_RESOURCE_GROUP }} `
            -DataFactoryName ${{ secrets.AZURE_FACTORY_NAME }} `
            -predeployment $true `
            -deleteDeployment $false

      - name: Deploy Azure Data Factory
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ${{ github.workspace }}/ARMTemplateForFactory.json
          parameters: ${{ github.workspace }}/ARMTemplateParametersForFactory.json factoryName=${{ secrets.AZURE_FACTORY_NAME }}

      - name: Post-deployment PowerShell Script
        shell: pwsh
        run: |
          ${{ github.workspace }}\PrePostDeploymentScript.Ver2.ps1 `
            -armTemplate "${{ github.workspace }}/ARMTemplateParametersForFactory.json" `
            -ResourceGroupName ${{ secrets.AZURE_RESOURCE_GROUP }} `
            -DataFactoryName ${{ secrets.AZURE_FACTORY_NAME }} `
            -predeployment $false `
            -deleteDeployment $true
